# Cloudflare Pages configuration
# This file tells Cloudflare how to build and deploy your project.
# You generally do not need to edit this file.

name = "climb-oral-exam"
compatibility_date = "2024-01-01"
pages_build_output_dir = "."
